FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY . .

RUN chmod +x mvnw || true
RUN ./mvnw package -DskipTests || mvn package -DskipTests

EXPOSE 8080

CMD ["java","-jar","target/sweetshop-0.0.1-SNAPSHOT.jar"]